[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[supervisord]
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor
nodaemon=true

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
stdout_logfile=/var/log/php-fpm.log
stderr_logfile=/var/log/php-fpm-error.log
priority=999

[program:laravel-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work --tries=3 --timeout=90
autostart=false
autorestart=false
numprocs=1
stdout_logfile=/var/www/storage/logs/queue-worker.log
user=www-data

[program:laravel-reverb]
command=php /var/www/artisan reverb:start --host=0.0.0.0 --port=8080 --no-interaction
autostart=false
autorestart=false
stdout_logfile=/var/www/storage/logs/reverb.log
user=www-data

[program:laravel-scheduler]
command=php /var/www/artisan schedule:work --no-interaction
autostart=false
autorestart=false
stdout_logfile=/var/www/storage/logs/scheduler.log
user=www-data
